<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="robot2_index.php" method="GET">
        <label for="robot_name">Entrez un nom pour votre robot:</label>
        <input type="text" name="robotName" id="robot_name">
        <button type="submit">Soumettre</button>
    </form>
    <?php require 'robot2_index.php'; ?>
</body>
</html>